name: Deploy Power Pages Solution to Developer Environment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest  # Better support for Microsoft CLI

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Power Platform CLI
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Import Solution to Developer Environment
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ secrets.DEV_ENVIRONMENT_URL }}
          tenant-id: ${{ secrets.TENANT_ID }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          solution-file: solutions/PowerPagesSiteSolution/MusandamDivingSolution.zip
